import { Preferences } from '@capacitor/preferences';
import { Device } from '@capacitor/device';

const DEVICE_KEY = 'krator_rewards_device_id';

/**
 * Returns a stable per-install identifier. Uses the native Android ID via
 * @capacitor/device when possible, falls back to a random UUID stored in
 * Preferences (so uninstall/reinstall creates a fresh account, which is fine
 * — the new account gets 5 welcome coins just like any new user).
 */
export async function getDeviceId(): Promise<string> {
  const cached = await Preferences.get({ key: DEVICE_KEY });
  if (cached.value) return cached.value;

  let id: string | null = null;
  try {
    const info = await Device.getId();
    // On Android this is the ANDROID_ID; on web it's a UUID generated by the plugin.
    id = info.identifier;
  } catch {
    // Ignored — fall through to browser UUID
  }
  if (!id) {
    id = (globalThis.crypto?.randomUUID?.() ?? `${Date.now()}-${Math.random().toString(36).slice(2)}`);
  }

  await Preferences.set({ key: DEVICE_KEY, value: id });
  return id;
}
